/**
 * Breed Labels - Vietnamese translations for ImageNet dog/cat classes
 * Dog breeds: ImageNet classes 151-268 (118 breeds)
 * Cat types: ImageNet classes 281-285 (5 types)
 */

const DOG_BREEDS = {
  151: { en: 'Chihuahua', vi: 'Chihuahua' },
  152: { en: 'Japanese Spaniel', vi: 'Nhật Bản Chin' },
  153: { en: 'Maltese', vi: 'Maltese' },
  154: { en: 'Pekingese', vi: 'Bắc Kinh' },
  155: { en: 'Shih Tzu', vi: 'Shih Tzu' },
  156: { en: 'King Charles Spaniel', vi: 'King Charles Spaniel' },
  157: { en: 'Papillon', vi: 'Papillon' },
  158: { en: 'Toy Terrier', vi: 'Toy Terrier' },
  159: { en: 'Rhodesian Ridgeback', vi: 'Rhodesian Ridgeback' },
  160: { en: 'Afghan Hound', vi: 'Chó săn Afghanistan' },
  161: { en: 'Basset Hound', vi: 'Basset Hound' },
  162: { en: 'Beagle', vi: 'Beagle' },
  163: { en: 'Bloodhound', vi: 'Bloodhound' },
  164: { en: 'Bluetick Coonhound', vi: 'Bluetick Coonhound' },
  165: { en: 'Black and Tan Coonhound', vi: 'Black and Tan Coonhound' },
  166: { en: 'Walker Foxhound', vi: 'Walker Foxhound' },
  167: { en: 'English Foxhound', vi: 'Chó săn cáo Anh' },
  168: { en: 'Redbone Coonhound', vi: 'Redbone Coonhound' },
  169: { en: 'Borzoi', vi: 'Borzoi' },
  170: { en: 'Irish Wolfhound', vi: 'Chó sói Ai-len' },
  171: { en: 'Italian Greyhound', vi: 'Greyhound Ý' },
  172: { en: 'Whippet', vi: 'Whippet' },
  173: { en: 'Ibizan Hound', vi: 'Chó săn Ibiza' },
  174: { en: 'Norwegian Elkhound', vi: 'Chó Elkhound Na Uy' },
  175: { en: 'Otterhound', vi: 'Otterhound' },
  176: { en: 'Saluki', vi: 'Saluki' },
  177: { en: 'Scottish Deerhound', vi: 'Chó săn hươu Scotland' },
  178: { en: 'Weimaraner', vi: 'Weimaraner' },
  179: { en: 'Staffordshire Bull Terrier', vi: 'Staffordshire Bull Terrier' },
  180: { en: 'American Staffordshire Terrier', vi: 'American Staffordshire Terrier' },
  181: { en: 'Bedlington Terrier', vi: 'Bedlington Terrier' },
  182: { en: 'Border Terrier', vi: 'Border Terrier' },
  183: { en: 'Kerry Blue Terrier', vi: 'Kerry Blue Terrier' },
  184: { en: 'Irish Terrier', vi: 'Irish Terrier' },
  185: { en: 'Norfolk Terrier', vi: 'Norfolk Terrier' },
  186: { en: 'Norwich Terrier', vi: 'Norwich Terrier' },
  187: { en: 'Yorkshire Terrier', vi: 'Yorkshire Terrier' },
  188: { en: 'Wire Fox Terrier', vi: 'Wire Fox Terrier' },
  189: { en: 'Lakeland Terrier', vi: 'Lakeland Terrier' },
  190: { en: 'Sealyham Terrier', vi: 'Sealyham Terrier' },
  191: { en: 'Airedale Terrier', vi: 'Airedale Terrier' },
  192: { en: 'Cairn Terrier', vi: 'Cairn Terrier' },
  193: { en: 'Australian Terrier', vi: 'Australian Terrier' },
  194: { en: 'Dandie Dinmont Terrier', vi: 'Dandie Dinmont Terrier' },
  195: { en: 'Boston Terrier', vi: 'Boston Terrier' },
  196: { en: 'Miniature Schnauzer', vi: 'Schnauzer Mini' },
  197: { en: 'Giant Schnauzer', vi: 'Schnauzer Khổng lồ' },
  198: { en: 'Standard Schnauzer', vi: 'Schnauzer Tiêu chuẩn' },
  199: { en: 'Scottish Terrier', vi: 'Scottish Terrier' },
  200: { en: 'Tibetan Terrier', vi: 'Tibetan Terrier' },
  201: { en: 'Australian Silky Terrier', vi: 'Silky Terrier Úc' },
  202: { en: 'Soft-coated Wheaten Terrier', vi: 'Wheaten Terrier' },
  203: { en: 'West Highland White Terrier', vi: 'West Highland Terrier' },
  204: { en: 'Lhasa Apso', vi: 'Lhasa Apso' },
  205: { en: 'Flat-coated Retriever', vi: 'Flat-coated Retriever' },
  206: { en: 'Curly-coated Retriever', vi: 'Curly-coated Retriever' },
  207: { en: 'Golden Retriever', vi: 'Golden Retriever' },
  208: { en: 'Labrador Retriever', vi: 'Labrador Retriever' },
  209: { en: 'Chesapeake Bay Retriever', vi: 'Chesapeake Bay Retriever' },
  210: { en: 'German Shorthaired Pointer', vi: 'Chó chỉ điểm Đức' },
  211: { en: 'Vizsla', vi: 'Vizsla' },
  212: { en: 'English Setter', vi: 'English Setter' },
  213: { en: 'Irish Setter', vi: 'Irish Setter' },
  214: { en: 'Gordon Setter', vi: 'Gordon Setter' },
  215: { en: 'Brittany Spaniel', vi: 'Brittany Spaniel' },
  216: { en: 'Clumber Spaniel', vi: 'Clumber Spaniel' },
  217: { en: 'English Springer Spaniel', vi: 'English Springer Spaniel' },
  218: { en: 'Welsh Springer Spaniel', vi: 'Welsh Springer Spaniel' },
  219: { en: 'Cocker Spaniel', vi: 'Cocker Spaniel' },
  220: { en: 'Sussex Spaniel', vi: 'Sussex Spaniel' },
  221: { en: 'Irish Water Spaniel', vi: 'Irish Water Spaniel' },
  222: { en: 'Kuvasz', vi: 'Kuvasz' },
  223: { en: 'Schipperke', vi: 'Schipperke' },
  224: { en: 'Groenendael', vi: 'Becgiê Bỉ Groenendael' },
  225: { en: 'Malinois', vi: 'Becgiê Bỉ Malinois' },
  226: { en: 'Briard', vi: 'Briard' },
  227: { en: 'Australian Kelpie', vi: 'Kelpie Úc' },
  228: { en: 'Komondor', vi: 'Komondor' },
  229: { en: 'Old English Sheepdog', vi: 'Chó chăn cừu Anh cổ' },
  230: { en: 'Shetland Sheepdog', vi: 'Shetland Sheepdog' },
  231: { en: 'Collie', vi: 'Collie' },
  232: { en: 'Border Collie', vi: 'Border Collie' },
  233: { en: 'Bouvier des Flandres', vi: 'Bouvier des Flandres' },
  234: { en: 'Rottweiler', vi: 'Rottweiler' },
  235: { en: 'German Shepherd', vi: 'Becgiê Đức' },
  236: { en: 'Doberman Pinscher', vi: 'Doberman' },
  237: { en: 'Miniature Pinscher', vi: 'Pinscher Mini' },
  238: { en: 'Greater Swiss Mountain Dog', vi: 'Chó núi Thuỵ Sĩ' },
  239: { en: 'Bernese Mountain Dog', vi: 'Bernese Mountain' },
  240: { en: 'Appenzeller Sennenhund', vi: 'Appenzeller' },
  241: { en: 'Entlebucher Mountain Dog', vi: 'Entlebucher' },
  242: { en: 'Boxer', vi: 'Boxer' },
  243: { en: 'Bull Mastiff', vi: 'Bull Mastiff' },
  244: { en: 'Tibetan Mastiff', vi: 'Ngao Tây Tạng' },
  245: { en: 'French Bulldog', vi: 'Bully Pháp' },
  246: { en: 'Great Dane', vi: 'Great Dane' },
  247: { en: 'St. Bernard', vi: 'St. Bernard' },
  248: { en: 'Alaskan Malamute', vi: 'Alaska Malamute' },
  249: { en: 'Siberian Husky', vi: 'Husky Sibir' },
  250: { en: 'Dalmatian', vi: 'Đốm (Dalmatian)' },
  251: { en: 'Affenpinscher', vi: 'Affenpinscher' },
  252: { en: 'Basenji', vi: 'Basenji' },
  253: { en: 'Pug', vi: 'Pug' },
  254: { en: 'Leonberger', vi: 'Leonberger' },
  255: { en: 'Newfoundland', vi: 'Newfoundland' },
  256: { en: 'Pyrenean Mountain Dog', vi: 'Chó núi Pyrenees' },
  257: { en: 'Samoyed', vi: 'Samoyed' },
  258: { en: 'Pomeranian', vi: 'Phốc Sóc (Pomeranian)' },
  259: { en: 'Chow Chow', vi: 'Chow Chow' },
  260: { en: 'Keeshond', vi: 'Keeshond' },
  261: { en: 'Brabancon Griffon', vi: 'Brabancon Griffon' },
  262: { en: 'Pembroke Welsh Corgi', vi: 'Corgi Pembroke' },
  263: { en: 'Cardigan Welsh Corgi', vi: 'Corgi Cardigan' },
  264: { en: 'Toy Poodle', vi: 'Poodle Toy' },
  265: { en: 'Miniature Poodle', vi: 'Poodle Mini' },
  266: { en: 'Standard Poodle', vi: 'Poodle Tiêu chuẩn' },
  267: { en: 'Mexican Hairless', vi: 'Chó trụi lông Mexico' },
  268: { en: 'Dingo', vi: 'Dingo' },
};

const CAT_BREEDS = {
  281: { en: 'Tabby Cat', vi: 'Mèo Mướp (Tabby)' },
  282: { en: 'Tiger Cat', vi: 'Mèo Vằn' },
  283: { en: 'Persian Cat', vi: 'Mèo Ba Tư' },
  284: { en: 'Siamese Cat', vi: 'Mèo Xiêm (Siamese)' },
  285: { en: 'Egyptian Mau', vi: 'Mèo Ai Cập (Egyptian Mau)' },
};

const DOG_CLASS_INDICES = Object.keys(DOG_BREEDS).map(Number);
const CAT_CLASS_INDICES = Object.keys(CAT_BREEDS).map(Number);

function getBreedName(classIdx) {
  const breed = DOG_BREEDS[classIdx] || CAT_BREEDS[classIdx];
  if (breed) return breed;
  return { en: 'Unknown', vi: 'Không xác định' };
}

module.exports = {
  DOG_BREEDS,
  CAT_BREEDS,
  DOG_CLASS_INDICES,
  CAT_CLASS_INDICES,
  getBreedName,
};
